### ISSUE TITLE
Can't compile samples: missing standard c++ headers

### ISSUE THREAD

**Issue by Natrocx** [codeplaysoftware/computecpp-sdk#244] opened 2020-09-03 15:56 UTC
Trying to build anything (for example the simple-vector-add example) will fail with the message `fatal error: 'cmath' file not found`.
The cmake command used to generate the build file is a simple `cmake .. -DComputeCpp_DIR=/usr -G Ninja`.

The complete output goes like this: 
```
ninja simple-vector-add
[1/3] Building ComputeCpp integration header file /home/natrocx/projects/computecpp-sdk/build/samples/simple-vector-add_simple-vector-add.cpp.sycl
FAILED: samples/simple-vector-add_simple-vector-add.cpp.bc samples/simple-vector-add_simple-vector-add.cpp.sycl
cd /home/natrocx/projects/computecpp-sdk/build/samples && /usr/bin/compute++ -sycl -O2 -mllvm -inline-threshold=1000 -intelspirmetadata -sycl-target spir64 -std=c++14 -I"/usr/include"	-I"/usr/include"  -sycl-ih /home/natrocx/projects/computecpp-sdk/build/samples/simple-vector-add_simple-vector-add.cpp.sycl -o /home/natrocx/projects/computecpp-sdk/build/samples/simple-vector-add_simple-vector-add.cpp.bc -c /home/natrocx/projects/computecpp-sdk/samples/simple-vector-add.cpp -MMD -MF /home/natrocx/projects/computecpp-sdk/build/samples/simple-vector-add_simple-vector-add.cpp.sycl.d -MT samples/simple-vector-add_simple-vector-add.cpp.bc
In file included from /home/natrocx/projects/computecpp-sdk/samples/simple-vector-add.cpp:30:
In file included from /usr/include/CL/sycl.hpp:1:
In file included from /usr/include/CL/../SYCL/sycl.hpp:20:
In file included from /usr/include/SYCL/sycl_builtins.h:27:
In file included from /usr/include/SYCL/cpp_to_cl_cast.h:12:
In file included from /usr/include/SYCL/deduce.h:25:
In file included from /usr/include/SYCL/cl_types.h:23:
In file included from /usr/include/SYCL/common.h:19:
/usr/include/SYCL/predefines.h:566:10: fatal error: 'cmath' file not found
#include <cmath>
         ^~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by DuncanMcBain** [comment] 2020-09-03 18:54
Hi @Natrocx ,
thanks for your bug report. Can I ask what system you're running? I normally see this issue when cross-compiling and a stray flag has managed to munge the include paths, but it doesn't look like you're cross compiling here.

I'm also unable to reproduce this locally with some fairly limited testing. I think I've avoided this problem by not putting ComputeCpp into a system location (like `/usr`) since I tend to upgrade and switch versions quite often.

If you can provide us some more information, we might be able to pin this down finally!

**Comment by Natrocx** [comment] 2020-09-04 11:18
Hi, thanks for taking the time to look at this.

I am running Clear Linux and this issue persists when using gcc and the standard environment set by Clear Linux as well as with clang and a custom environment as host compiler. I am in fact not cross compiling.

I have also tried placing the computecpp installation at /usr/local/computecpp/ComputeCpp-CE-2.1.0-x86_64-linux-gnu to separate it from the system installation, which does not yield a different result.

Here is the output of env with gcc (stripped to possibly interesting variables): 
```
SHELL=/bin/bash
MPI_LIBS=/usr/lib64/libmpi.so
LA_INCLUDE=/usr/include
MPI_CC=/usr/bin/mpicc
MPI_VERSION=3.2
FFLAGS=-g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -malign-data=abi -fno-semantic-interposition -ftree-vectorize -ftree-loop-vectorize -Wl,--enable-new-dtags -Wa,-mbranches-within-32B-boundaries
MODULESHOME=/usr/share/modules
MANPATH=/usr/share/man:
CXX=g++
CXXFLAGS=-g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects -fno-trapping-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake -Wa,-mbranches-within-32B-boundaries -fvisibility-inlines-hidden -Wl,--enable-new-dtags
MPI_INCLUDE=/usr/include/
LA_LIBS=/usr/lib64/libopenblas.so.0
MPI_PATH=/usr/lib64/
FCFLAGS=-g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -malign-data=abi -fno-semantic-interposition -ftree-vectorize -ftree-loop-vectorize -Wl,-sort-common -Wl,--enable-new-dtags
MODULEPATH_modshare=/usr/share/modules/modulefiles:1
AR=gcc-ar
NM=gcc-nm
BASH_ENV=/usr/share/modules/init/bash
LA_PATH=/usr/lib64/
LD_LIBRARY_PATH=:/usr/lib/x86_64-linux-gnu/:/usr/local/lib
GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01
MODULEPATH=/usr/share/modules/modulefiles
CC=gcc
CFLAGS=-g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects -fno-trapping-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake -Wa,-mbranches-within-32B-boundaries
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
LA_VERSION=OpenBLAS
THEANO_FLAGS=floatX=float32,openmp=true,gcc.cxxflags="-ftree-vectorize -mavx"
RANLIB=gcc-ranlib
```
And here with clang as host toolchain:
```
MPI_LIBS=/usr/lib64/libmpi.so
LA_INCLUDE=/usr/include
MPI_CC=/usr/bin/mpicc
MPI_VERSION=3.2
FFLAGS=-g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -malign-data=abi -fno-semantic-interposition -ftree-vectorize -ftree-loop-vectorize -Wl,--enable-new-dtags -Wa,-mbranches-within-32B-boundaries
MODULESHOME=/usr/share/modules
CXX=/usr/local/bin/clang++
CXXFLAGS=-O3 -pipe -fexceptions -march=native -fasynchronous-unwind-tables
MPI_INCLUDE=/usr/include/
LA_LIBS=/usr/lib64/libopenblas.so.0
MPI_PATH=/usr/lib64/
FCFLAGS=-g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -malign-data=abi -fno-semantic-interposition -ftree-vectorize -ftree-loop-vectorize -Wl,-sort-common -Wl,--enable-new-dtags
MODULEPATH_modshare=/usr/share/modules/modulefiles:1
AR=/usr/local/bin/llvm-ar
AS=/usr/local/bin/llvm-as
NM=gcc-nm
BASH_ENV=/usr/share/modules/init/bash
LA_PATH=/usr/lib64/
LD_LIBRARY_PATH=:/usr/lib/x86_64-linux-gnu/:/usr/local/lib
XDG_RUNTIME_DIR=/run/user/1000
GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01
PATH=/home/natrocx/.cargo/bin:/home/natrocx/.cargo/bin:/usr/bin/haswell:/usr/local/bin:/usr/bin:/opt/3rd-party/bin:/home/natrocx/.local/bin:/snap/bin:/opt/gradle/bin:/home/natrocx/apps/flutter/bin:/home/natrocx/apps/android-studio/bin:/home/natrocx/.local/bin:/home/natrocx/.cabal/bin:/opt/nvidia/bin:/home/natrocx/apps/depot_tools
MODULEPATH=/usr/share/modules/modulefiles
CC=/usr/local/bin/clang
CFLAGS=-O3 -pipe -fexceptions -march=native -fasynchronous-unwind-tables
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
LA_VERSION=OpenBLAS
KDE_APPLICATIONS_AS_SCOPE=1
THEANO_FLAGS=floatX=float32,openmp=true,gcc.cxxflags="-ftree-vectorize -mavx"
RANLIB=/usr/local/bin/llvm-ranlib
```
I do use lld as my system linker however that should not influence resolution of includes.

**Comment by Natrocx** [comment] 2020-09-04 20:06
In my experience this issue usually occurs when running a compiler in C mode instead of C++. 
The c++ standard headers are obviously not included in the paths supplied by the `-I...` of the build command since this only references /usr/include and not /usr/include/c++/10/ or similar. 

Could this possibly be the root of the issue?

**Comment by Natrocx** [comment] 2020-09-07 20:47
I think I might have misstated that slightly. While I am (obviously) able to compile normal C++ code, I did in fact not successfully compile a sycl program yet. (Intel's dpc++ is failing to build too for a number of reasons.)

However I do know this issue from using a custom toolchain to build C++ programs. If one were to specify clang instead of clang++ as the C++ compiler, the toolchain would not scan the include/c++/10/ directory automatically and thus miss all C++ standard library headers as is the case in this bug.

That being said, I have no clue if this is an issue with the build system (cmake makes me want to cry) or the compiler.

**Comment by rodburns** [comment] 2020-09-09 12:34
> That being said, I have no clue if this is an issue with the build system (cmake makes me want to cry) or the compiler.

It's possible it is either. If you have a non-standard toolchain that could cause some behavior we don't expect. I'm not sure what else to suggest unfortunately.

**Comment by mcleary** [comment] 2020-09-09 13:08
@Natrocx could you paste here the exact command line that is failing? Is that the one from the first post?

**Comment by Natrocx** [comment] 2020-09-09 14:16
@mcleary yes it is the one from the first post. 

I have included both the cmake generator command line and the actual failing compiler command

**Comment by mcleary** [comment] 2020-09-09 14:55
I see. Which custom toolchain are you using then?

**Comment by Natrocx** [comment] 2020-09-09 20:15
I have tried building with the system clang and GCC (installed under standard paths) and a recent git snapshot of clang.

None have been successful.

**Comment by mcleary** [comment] 2020-09-09 21:05
Could you try to call `compute++` in the command line without the `-I /usr/local` etc just to see what the compiler is going to tell you? 

Unfortunately the only way for us to debug this properly would be in a VM like environment

**Comment by rodburns** [comment] 2021-03-22 09:48
Since this has been dormant for quite a long time I am closing this issue however please feel free to re-open or submit a new issue if you still need help. Thanks.

**Closed by rodburns** 2021-03-22 09:48 UTC
